#!/bin/bash

# This application will prepare an input file for downloading .xm-files

TMP_FILE="tmp.html"
URL=""
EXT=""

function print_help {
	echo "
gen-input is a utility for creating an input file containing links for 
scraper to use.

Usage:
	-u) Url
	-e) File extension of interest
	-h) This help page
";
}

function generate_input_file {
	curl "$URL" > "$TMP_FILE"
	grep -e "http.*\.$EXT" "$TMP_FILE" > "2$TMP_FILE" 
	mv "2$TMP_FILE" "$TMP_FILE"
	sed 's/.*href="//g' "$TMP_FILE" | sed 's/".*//g' > input
	rm "$TMP_FILE"
}

while getopts hu:e: option; do
	case ${option} in
		u) URL="$OPTARG";;
		e) EXT="$OPTARG";;
		h) print_help; exit;;
	esac
done

if [ "$URL" = "" ]; then
	echo "You have to give a url to download the raw html from";
	exit 1;
fi

if [ "$EXT" = "" ]; then
	echo "You have to give a file extension";
	exit 1;
fi

generate_input_file;
echo "Done!";
