#!/bin/bash

# This application will prepare an input file for downloading with scraper 

TMP_FILE="tmp.html"
URL=""
EXTS=""

function print_help {
	echo "
gen-input is a utility for creating an input file containing links for 
scraper to use.

Usage:
	-u) Url
	-s) Run silently
	-h) This help page

The remaining arguments will be treated as the desired file extensions

Example:
	$ ./gen-input -u http://example.com/somePath.html xm mod it 
	$ ./gen-input -u http://example.com/someOtherPath.html ogg mp3 m4a 
";
}

function generate_input_file {
	curl -s "$URL" > "$TMP_FILE"

	for EXT in $EXTS; do
		grep -e "\"http.*\.$EXT\"" "$TMP_FILE" >> "2$TMP_FILE" 
	done

	mv "2$TMP_FILE" "$TMP_FILE"
	sed 's/.*href="//g' "$TMP_FILE" | sed 's/".*//g' >> input
	rm "$TMP_FILE"
}

while getopts shu: option; do
	case ${option} in
		u) URL="$OPTARG";;
		s) SILENT=true;;
		h) print_help; exit;;
	esac
done
shift $(($OPTIND - 1));
EXTS="$@";

if [ "$URL" = "" ]; then
	echo "You have to give a url to download the raw html from";
	exit 1;
fi

if [ "$EXTS" = "" ]; then
	echo "You have to give at least one file extension";
	exit 1;
fi

generate_input_file;
if [ ! $SILENT ]; then
	echo "Done!";
fi
