#!/bin/bash

TMP_FILE="tmp.html"

if [ "$1" = "" ]; then
	echo "You have to give a link to the source";
	exit 1;
elif [ "$1" = "-h" ]; then
	echo "
Usage:
	$ gen-input \"http://example.com/some-path.html\"
";
	exit;
fi

curl "$1" > "$TMP_FILE"
grep -e 'http.*\.xm' "$TMP_FILE" > "2$TMP_FILE" 
mv "2$TMP_FILE" "$TMP_FILE"
sed 's/.*href="//g' "$TMP_FILE" | sed 's/".*//g' > input
rm "$TMP_FILE"
